2021-07-29 14:51:37,942 - 1 - hummingbot.client.hummingbot_application - INFO - start command initiated.
2021-07-29 14:51:38,248 - 1 - hummingbot.connector.exchange.binance.binance_exchange - INFO - Network status has changed to NetworkStatus.CONNECTED. Starting networking...
2021-07-29 14:51:38,516 - 1 - hummingbot.connector.exchange.binance.binance_order_book_tracker - INFO - Initialized order book for XEM-BTC. 1/1 completed.
2021-07-29 14:51:38,521 - 1 - hummingbot.connector.exchange.binance.binance_api_user_stream_data_source - INFO - Reconnecting to wss://stream.binance.com:9443/ws/vclI9YDcmvotxiGuU8VvjMYlGSZnEokPqF4fDkxz9Doo7QSXMGIthvR5hxBb.
2021-07-29 14:51:40,414 - 1 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (XEM-BTC) Creating 3 bid orders at (Size, Price): ['579 XEM, 0.00000404 BTC', '579 XEM, 0.00000403 BTC', '579 XEM, 0.00000403 BTC']
2021-07-29 14:51:41,829 - 1 - hummingbot.connector.exchange.binance.binance_exchange - INFO - Created LIMIT_MAKER BUY order x-XEKWYICX-BXMBC1627570300415648 for 579.00000000 XEM-BTC.
2021-07-29 14:51:41,834 - 1 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1627570301.0, "type": "OrderType.LIMIT_MAKER", "trading_pair": "XEM-BTC", "amount": "579.00000000", "price": "0.00000404", "order_id": "x-XEKWYICX-BXMBC1627570300415648", "exchange_order_id": "168936314", "leverage": 1, "position": "NILL", "event_name": "BuyOrderCreatedEvent", "event_source": "binance"}
2021-07-29 14:51:42,330 - 1 - hummingbot.connector.exchange.binance.binance_exchange - INFO - Created LIMIT_MAKER BUY order x-XEKWYICX-BXMBC1627570300425074 for 579.00000000 XEM-BTC.
2021-07-29 14:51:42,330 - 1 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1627570302.0, "type": "OrderType.LIMIT_MAKER", "trading_pair": "XEM-BTC", "amount": "579.00000000", "price": "0.00000403", "order_id": "x-XEKWYICX-BXMBC1627570300425074", "exchange_order_id": "168936316", "leverage": 1, "position": "NILL", "event_name": "BuyOrderCreatedEvent", "event_source": "binance"}
2021-07-29 14:51:42,831 - 1 - hummingbot.connector.exchange.binance.binance_exchange - INFO - Created LIMIT_MAKER BUY order x-XEKWYICX-BXMBC1627570300425200 for 579.00000000 XEM-BTC.
2021-07-29 14:51:42,831 - 1 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1627570302.0, "type": "OrderType.LIMIT_MAKER", "trading_pair": "XEM-BTC", "amount": "579.00000000", "price": "0.00000403", "order_id": "x-XEKWYICX-BXMBC1627570300425200", "exchange_order_id": "168936319", "leverage": 1, "position": "NILL", "event_name": "BuyOrderCreatedEvent", "event_source": "binance"}
2021-07-29 14:52:42,782 - 1 - hummingbot.client.hummingbot_application - ERROR - list index out of range
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/client/hummingbot_application.py", line 142, in _handle_command
    if command_split[0] == s['command']:
IndexError: list index out of range
2021-07-29 14:52:42,978 - 1 - hummingbot.client.hummingbot_application - ERROR - list index out of range
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/client/hummingbot_application.py", line 142, in _handle_command
    if command_split[0] == s['command']:
IndexError: list index out of range
2021-07-29 14:52:55,256 - 1 - hummingbot.client.hummingbot_application - INFO - stop command initiated.
2021-07-29 14:52:55,500 - 1 - hummingbot.connector.exchange.binance.binance_exchange - INFO - Successfully cancelled order x-XEKWYICX-BXMBC1627570300415648.
2021-07-29 14:52:55,515 - 1 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1627570375.0, "order_id": "x-XEKWYICX-BXMBC1627570300415648", "exchange_order_id": null, "event_name": "OrderCancelledEvent", "event_source": "binance"}
2021-07-29 14:52:56,001 - 1 - hummingbot.connector.exchange.binance.binance_exchange - INFO - Successfully cancelled order x-XEKWYICX-BXMBC1627570300425074.
2021-07-29 14:52:56,014 - 1 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1627570376.0, "order_id": "x-XEKWYICX-BXMBC1627570300425074", "exchange_order_id": null, "event_name": "OrderCancelledEvent", "event_source": "binance"}
2021-07-29 14:52:56,502 - 1 - hummingbot.connector.exchange.binance.binance_exchange - INFO - Successfully cancelled order x-XEKWYICX-BXMBC1627570300425200.
2021-07-29 14:52:56,515 - 1 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1627570376.0, "order_id": "x-XEKWYICX-BXMBC1627570300425200", "exchange_order_id": null, "event_name": "OrderCancelledEvent", "event_source": "binance"}
2021-07-29 14:58:13,948 - 1 - hummingbot.client.hummingbot_application - INFO - start command initiated.
2021-07-29 14:58:14,687 - 1 - hummingbot.connector.exchange.binance.binance_exchange - INFO - Network status has changed to NetworkStatus.CONNECTED. Starting networking...
2021-07-29 14:58:14,963 - 1 - hummingbot.connector.exchange.binance.binance_api_user_stream_data_source - INFO - Reconnecting to wss://stream.binance.com:9443/ws/vclI9YDcmvotxiGuU8VvjMYlGSZnEokPqF4fDkxz9Doo7QSXMGIthvR5hxBb.
2021-07-29 14:58:14,971 - 1 - hummingbot.connector.exchange.binance.binance_order_book_tracker - INFO - Initialized order book for XEM-BTC. 1/1 completed.
2021-07-29 14:58:16,012 - 1 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (XEM-BTC) Creating 3 bid orders at (Size, Price): ['579 XEM, 0.00000404 BTC', '579 XEM, 0.00000403 BTC', '579 XEM, 0.00000403 BTC']
2021-07-29 14:58:16,954 - 1 - hummingbot.connector.exchange.binance.binance_exchange - NETWORK - Error submitting BUY LIMIT_MAKER order to Binance for 579.00000000 XEM-BTC 0.00000404.
Traceback (most recent call last):
  File "hummingbot/connector/exchange/binance/binance_exchange.pyx", line 887, in hummingbot.connector.exchange.binance.binance_exchange.BinanceExchange.create_order
    order_result = await self.query_api(self._binance_client.create_order, **api_params)
  File "hummingbot/connector/exchange/binance/binance_exchange.pyx", line 229, in query_api
    async with self._throttler.weighted_task(request_weight=request_weight):
  File "hummingbot/connector/exchange/binance/binance_exchange.pyx", line 241, in hummingbot.connector.exchange.binance.binance_exchange.BinanceExchange.query_api
    raise ex
  File "hummingbot/connector/exchange/binance/binance_exchange.pyx", line 231, in hummingbot.connector.exchange.binance.binance_exchange.BinanceExchange.query_api
    return await self._async_scheduler.call_async(partial(func, *args, **kwargs),
  File "/home/hummingbot/hummingbot/core/utils/async_call_scheduler.py", line 128, in call_async
    return await self.schedule_async_call(coro, timeout_seconds, app_warning_msg=app_warning_msg)
  File "/home/hummingbot/hummingbot/core/utils/async_call_scheduler.py", line 117, in schedule_async_call
    return await fut
  File "/home/hummingbot/hummingbot/core/utils/async_call_scheduler.py", line 80, in _coro_scheduler
    fut.set_result(await coro)
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/site-packages/binance/client.py", line 1201, in create_order
    return self._post('order', True, data=params)
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/site-packages/binance/client.py", line 240, in _post
    return self._request_api('post', path, signed, version, **kwargs)
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/site-packages/binance/client.py", line 202, in _request_api
    return self._request(method, uri, signed, **kwargs)
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/site-packages/binance/client.py", line 197, in _request
    return self._handle_response()
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/site-packages/binance/client.py", line 230, in _handle_response
    raise BinanceAPIException(self.response)
binance.exceptions.BinanceAPIException: APIError(code=-2015): Invalid API-key, IP, or permissions for action.
2021-07-29 14:58:16,962 - 1 - hummingbot.connector.exchange.binance.binance_exchange - WARNING - APIError(code=-2015): Invalid API-key, IP, or permissions for action.
2021-07-29 14:58:17,454 - 1 - hummingbot.connector.exchange.binance.binance_exchange - NETWORK - Error submitting BUY LIMIT_MAKER order to Binance for 579.00000000 XEM-BTC 0.00000403.
Traceback (most recent call last):
  File "hummingbot/connector/exchange/binance/binance_exchange.pyx", line 887, in hummingbot.connector.exchange.binance.binance_exchange.BinanceExchange.create_order
    order_result = await self.query_api(self._binance_client.create_order, **api_params)
  File "hummingbot/connector/exchange/binance/binance_exchange.pyx", line 229, in query_api
    async with self._throttler.weighted_task(request_weight=request_weight):
  File "hummingbot/connector/exchange/binance/binance_exchange.pyx", line 241, in hummingbot.connector.exchange.binance.binance_exchange.BinanceExchange.query_api
    raise ex
  File "hummingbot/connector/exchange/binance/binance_exchange.pyx", line 231, in hummingbot.connector.exchange.binance.binance_exchange.BinanceExchange.query_api
    return await self._async_scheduler.call_async(partial(func, *args, **kwargs),
  File "/home/hummingbot/hummingbot/core/utils/async_call_scheduler.py", line 128, in call_async
    return await self.schedule_async_call(coro, timeout_seconds, app_warning_msg=app_warning_msg)
  File "/home/hummingbot/hummingbot/core/utils/async_call_scheduler.py", line 117, in schedule_async_call
    return await fut
  File "/home/hummingbot/hummingbot/core/utils/async_call_scheduler.py", line 80, in _coro_scheduler
    fut.set_result(await coro)
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/site-packages/binance/client.py", line 1201, in create_order
    return self._post('order', True, data=params)
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/site-packages/binance/client.py", line 240, in _post
    return self._request_api('post', path, signed, version, **kwargs)
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/site-packages/binance/client.py", line 202, in _request_api
    return self._request(method, uri, signed, **kwargs)
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/site-packages/binance/client.py", line 197, in _request
    return self._handle_response()
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/site-packages/binance/client.py", line 230, in _handle_response
    raise BinanceAPIException(self.response)
binance.exceptions.BinanceAPIException: APIError(code=-2015): Invalid API-key, IP, or permissions for action.
2021-07-29 14:58:17,454 - 1 - hummingbot.connector.exchange.binance.binance_exchange - WARNING - APIError(code=-2015): Invalid API-key, IP, or permissions for action.
2021-07-29 14:58:17,956 - 1 - hummingbot.connector.exchange.binance.binance_exchange - NETWORK - Error submitting BUY LIMIT_MAKER order to Binance for 579.00000000 XEM-BTC 0.00000403.
Traceback (most recent call last):
  File "hummingbot/connector/exchange/binance/binance_exchange.pyx", line 887, in hummingbot.connector.exchange.binance.binance_exchange.BinanceExchange.create_order
    order_result = await self.query_api(self._binance_client.create_order, **api_params)
  File "hummingbot/connector/exchange/binance/binance_exchange.pyx", line 229, in query_api
    async with self._throttler.weighted_task(request_weight=request_weight):
  File "hummingbot/connector/exchange/binance/binance_exchange.pyx", line 241, in hummingbot.connector.exchange.binance.binance_exchange.BinanceExchange.query_api
    raise ex
  File "hummingbot/connector/exchange/binance/binance_exchange.pyx", line 231, in hummingbot.connector.exchange.binance.binance_exchange.BinanceExchange.query_api
    return await self._async_scheduler.call_async(partial(func, *args, **kwargs),
  File "/home/hummingbot/hummingbot/core/utils/async_call_scheduler.py", line 128, in call_async
    return await self.schedule_async_call(coro, timeout_seconds, app_warning_msg=app_warning_msg)
  File "/home/hummingbot/hummingbot/core/utils/async_call_scheduler.py", line 117, in schedule_async_call
    return await fut
  File "/home/hummingbot/hummingbot/core/utils/async_call_scheduler.py", line 80, in _coro_scheduler
    fut.set_result(await coro)
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/site-packages/binance/client.py", line 1201, in create_order
    return self._post('order', True, data=params)
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/site-packages/binance/client.py", line 240, in _post
    return self._request_api('post', path, signed, version, **kwargs)
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/site-packages/binance/client.py", line 202, in _request_api
    return self._request(method, uri, signed, **kwargs)
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/site-packages/binance/client.py", line 197, in _request
    return self._handle_response()
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/site-packages/binance/client.py", line 230, in _handle_response
    raise BinanceAPIException(self.response)
binance.exceptions.BinanceAPIException: APIError(code=-2015): Invalid API-key, IP, or permissions for action.
2021-07-29 14:58:17,958 - 1 - hummingbot.connector.exchange.binance.binance_exchange - WARNING - APIError(code=-2015): Invalid API-key, IP, or permissions for action.
